### ISSUE TITLE
Signing key changed

### ISSUE THREAD

**Issue by linsui** [project-kaat/gpsdRelay#7]
The 1.2 apk is signed with a new key. What happens?

**Comment by project-kaat** [comment]
Short story:
Lost the old one.

Long story:
The key was stored on my linux workstation, where the 1.0 version was built.
I had to work on v1.1 from a random windows machine, so I moved the keystore to a shared NAS for convenience.
Since then, both machines got nuked many times because I like to switch operating systems a lot.
The NAS, however, stands unchanged. But the file is nowhere to be found.
_(which is quite puzzling, really. I know the exact filepath where it should be but it's just not there, nor in any of the backups)_
**My best guess is: at some point during storage cleanup I was just being an idiot and deleted it.**

**Comment by linsui** [comment]
Could you please send an email from unsad.me@protonmail.com to [team@f-droid.org](mailto:team@f-droid.org)?

**Comment by project-kaat** [comment]
> Could you please send an email from [unsad.me@protonmail.com](mailto:unsad.me@protonmail.com) to [team@f-droid.org](mailto:team@f-droid.org)?

Here's the verification number: `264282`.
Thanks for the support!

**Comment by linsui** [comment]
Thanks, updated. :)
